### ISSUE TITLE
ZSH bcd:2: = not found

### ISSUE THREAD

**Issue by nishad** [a1ecbr0wn/bcd#37]
When try to use bcd in zsh, it gives an error

```
> cd /some/dir
> bcd somedir
bcd:2: = not found
```

Verified that `eval "$(bookmark-cd init)"` is present in `.zshrc`.

However, directly using `bookmark-cd` works as expected :
```
> cd /some/dir
> bookmark-cd -s somedir
Bookmark saved
> cd ~
> $(bookmark-cd dcweb)
> pwd
/some/dir
```

**Comment by a1ecbr0wn** [comment]
This has now been fixed in release v0.2.11.
If you installed from homebrew you just need to run `brew upgrade`, if you installed via snapcraft, that release will be available within the hour
