### ISSUE TITLE
bcd requires -s to save a bookmark

### ISSUE THREAD

**Issue by nishad** [a1ecbr0wn/bcd#39]
In the [README.md](https://github.com/a1ecbr0wn/bcd/blob/4cf7e93fde4a87494e5d901d9cc6c981ccb73dc6/README.md?plain=1#L86), it should be 

```
cd /var/log
bcd -s logs
```

instead of

https://github.com/a1ecbr0wn/bcd/blob/4cf7e93fde4a87494e5d901d9cc6c981ccb73dc6/README.md?plain=1#L85-L86

Otherwise, in zsh, `bcd` gives 

```
Bookmark not found, use `--list` to see the list of bookmarks
```

**Comment by a1ecbr0wn** [comment]
Thank you for raising this, you are absolutely correct.
